package com.learnexo.model.core;


public enum ActivityType {
    POST,ANSWER,CRACK,QUESTION,CHALLENGE,
    UP_VOTE,DOWN_VOTE,COMMENT,SHARE,BOOKMARK,
    FOLLOW,UN_FOLLOW,BLOCK,TAG,SEARCH,

    DELETE,EDIT,TURN_ON_NOTIFICATIONS,TURN_OFF_NOTIFICATIONS,
    ANSWER_LATER,ANSWER_ANONYMOUSLY,
    REQ_QUES,PASS_QUES,MERGE_QUES,COMMENT_ON_QUES,
    REPORT,FOLLOW_PRIVATELY,VIEW_STATUS_LOG,

    SUBSCRIBE,COMPLETE_SUB,COMPLETE_TEST,
    ADD_IVQ,ADD_TEST_Q,
    REQUEST_HELP,GUIDE,
    PROFILE_UPDATE,INTEREST_UPDATE
}
