package com.learnexo.model.core;

import java.util.Date;
import java.util.List;

public class Post {
    //can be auto generated by firestore
    private String userId;
    private boolean is_notifiable;
    private Report report;

    private Date postedDate;
    private String postContent;

    private List<String> imageUrls;
    private List<String> tagList;

    private List<UpVote> upVoteList;
    private List<DownVote> downVoteList;
    private List<Comment> commentList;
    private List<Share> shareList;
    private List<Bookmark> bookmarkList;


}
