package com.learnexo.model.core;

import com.learnexo.model.user.Follower;
import com.learnexo.model.user.UserId;

import java.util.Date;
import java.util.List;

public class Question {
    private boolean isChallenge;
    //can be auto generated by firestore
    private UserId userId;
    private boolean is_notifiable;

    private Date postedDate;

    private List<String> imageUrls;
    private List<Tag> tagList;

//    private List<UpVote> upVoteList;
//    private List<DownVote> downVoteList;
//    private List<Comment> commentList;
//    private List<Share> shareList;
//    private List<Bookmark> bookmarkList;

    private List<Answer> answerList;
    private List<Follower> followerList;
}
